use_frameworks!

platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hengyudianzi/HYComponentsSpecs.git'
source 'https://github.com/cloudkite/Masonry.git'


target 'HYComponents_Example' do
  pod 'HYComponents', :path => '../'

  target 'HYComponents_Tests' do
    inherit! :search_paths
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end




